// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtBUFqXwD6f8rXH-nspG2DvmFLtusYw28',
    appId: '1:5365188659:web:118139f39b85b767e63b46',
    messagingSenderId: '5365188659',
    projectId: 'kuchbhi-86004',
    authDomain: 'kuchbhi-86004.firebaseapp.com',
    storageBucket: 'kuchbhi-86004.firebasestorage.app',
    measurementId: 'G-LXEEQC8WGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGZ6RL_dDGD5gH8cRtyM4Hr9k4w8x8nlk',
    appId: '1:5365188659:android:a4ce849203bf8ccae63b46',
    messagingSenderId: '5365188659',
    projectId: 'kuchbhi-86004',
    storageBucket: 'kuchbhi-86004.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-OMK_zx8yWb8RgfBrgkviABGoi4t9LkY',
    appId: '1:5365188659:ios:e7b128ec17d99dd1e63b46',
    messagingSenderId: '5365188659',
    projectId: 'kuchbhi-86004',
    storageBucket: 'kuchbhi-86004.firebasestorage.app',
    iosBundleId: 'com.example.kuchbhi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-OMK_zx8yWb8RgfBrgkviABGoi4t9LkY',
    appId: '1:5365188659:ios:e7b128ec17d99dd1e63b46',
    messagingSenderId: '5365188659',
    projectId: 'kuchbhi-86004',
    storageBucket: 'kuchbhi-86004.firebasestorage.app',
    iosBundleId: 'com.example.kuchbhi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtBUFqXwD6f8rXH-nspG2DvmFLtusYw28',
    appId: '1:5365188659:web:ae7df647146bf7e3e63b46',
    messagingSenderId: '5365188659',
    projectId: 'kuchbhi-86004',
    authDomain: 'kuchbhi-86004.firebaseapp.com',
    storageBucket: 'kuchbhi-86004.firebasestorage.app',
    measurementId: 'G-YZJX6FJY36',
  );
}
